[workspace]
members = [ "build/rapier2d", "build/rapier2d-f64", "build/rapier_testbed2d", "examples2d", "benchmarks2d",
            "build/rapier3d", "build/rapier3d-f64", "build/rapier_testbed3d", "examples3d", "benchmarks3d" ]

[patch.crates-io]
#wrapped2d = { git = "https://github.com/Bastacyclop/rust_box2d.git" }
#simba = { path = "../simba" }
ncollide2d = { path = "../ncollide/build/ncollide2d" }
ncollide3d = { path = "../ncollide/build/ncollide3d" }
nphysics2d = { path = "../nphysics/build/nphysics2d" }
nphysics3d = { path = "../nphysics/build/nphysics3d" }
kiss3d = { path = "../kiss3d" }
cdl2d = { path = "../cdl/build/cdl2d" }
cdl3d = { path = "../cdl/build/cdl3d" }
cdl2d-f64 = { path = "../cdl/build/cdl2d-f64" }
cdl3d-f64 = { path = "../cdl/build/cdl3d-f64" }
#cdl2d = { git = "https://github.com/sebcrozet/cdl.git" }
#cdl3d = { git = "https://github.com/sebcrozet/cdl.git" }
#cdl2d-f64 = { git = "https://github.com/sebcrozet/cdl.git" }
#cdl3d-f64 = { git = "https://github.com/sebcrozet/cdl.git" }
#nalgebra = { path = "../nalgebra" }

[profile.release]
#debug = true
codegen-units = 1
#opt-level = 1
#lto = true


#[profile.dev.package.rapier3d]
#opt-level = 3
#
#[profile.dev.package.kiss3d]
#opt-level = 3