[workspace]
members = [ "build/rapier2d", "build/rapier_testbed2d", "examples2d", "benchmarks2d",
            "build/rapier3d", "build/rapier_testbed3d", "examples3d", "benchmarks3d" ]

[patch.crates-io]
#wrapped2d = { git = "https://github.com/Bastacyclop/rust_box2d.git" }
#simba = { path = "../simba" }

[profile.release]
#debug = true
codegen-units = 1
#opt-level = 1
#lto = true


#[profile.dev.package.rapier3d]
#opt-level = 3
#
#[profile.dev.package.kiss3d]
#opt-level = 3