[workspace]
members = [ "build/rapier2d", "build/rapier_testbed2d", "examples2d", "benchmarks2d",
            "build/rapier3d", "build/rapier_testbed3d", "examples3d", "benchmarks3d" ]

[patch.crates-io]
#wrapped2d = { git = "https://github.com/Bastacyclop/rust_box2d.git" }
#simba = { path = "../simba" }
#ncollide2d = { path = "../ncollide/build/ncollide2d" }
#ncollide3d = { path = "../ncollide/build/ncollide3d" }
#nphysics2d = { path = "../nphysics/build/nphysics2d" }
#nphysics3d = { path = "../nphysics/build/nphysics3d" }
#kiss3d = { path = "../kiss3d" }
salva2d = { path = "../salva/build/salva2d" }
salva3d = { path = "../salva/build/salva3d" }

[profile.release]
#debug = true
codegen-units = 1
#opt-level = 1
#lto = true


#[profile.dev.package.rapier3d]
#opt-level = 3
#
#[profile.dev.package.kiss3d]
#opt-level = 3